In [8]:
import numpy as np

In [9]:
import numpy as np

arr = np.array([1, 5, 3, 5, 6, 8, 7])
print(arr)

[1 5 3 5 6 8 7]


In [10]:
matrix = np.array([[1, 5, 6],
                   [5, 6, 8],
                   [2, 6, 7]])
print(matrix)

[[1 5 6]
 [5 6 8]
 [2 6 7]]


In [11]:
import numpy as np

# Broadcasting (NumPy magic)
scores = np.array([12, 32, 65, 45, 95, 15, 75, 37])

bonus = scores + 5
print(bonus)

#Instead of looping, we can directly add a scalar (single value) to a numpy array.
# Numpy automatically broadcasts the value to match the array's shape.
arr_2D = np.array([[80, 90, 85],
                   [70, 60, 50],
                   [88, 76, 95]])

grace = np.array([2, 3, 4]) # add every column value !
result = arr_2D + grace
print(result)

[ 17  37  70  50 100  20  80  42]
[[82 93 89]
 [72 63 54]
 [90 79 99]]


In [ ]:
# Vectorization & Handling Missing Values ?

arr = np.arange(1, 1000001)
squared = arr **2
print(squared)

# Vectorization means replacing lopps with array opertions.
# This makes code shorter, cleaner and thousands of time faster.

# Handling Missing Values ?

# In real world datasets (Excel, Csv, Database), we often have missing values (nan)
#Numpy gives us tools to direct and handle them
data = np.array([10, 30, np.nan, 70, np.nan, 10])
print(data)

# Detect missing value!
print(np.isnan(data))

#Count missing values!
print(np.isnan(data).sum())

#Replace nan with mean
mean = np.nanmean(data)
clean = np.where(np.isnan(data), mean, data)
clean

[            1             4             9 ...  999996000004  999998000001
 1000000000000]
[10. 30. nan 70. nan 10.]
[False False  True False  True False]
2


array([10., 30., 30., 70., 30., 10.])

In [ ]:
# Performance Optimization 
# This is heavly used in Data Science preprocessing.
# Performance optimization !
import time 
arr = np.arange(1, 1000001)

#Vectorization :--
start = time.time()
square = arr ** 2
end = time.time()

print(end-start)


0.017354726791381836
