<a href="https://colab.research.google.com/github/codewithvishuuu/ML-crash-course/blob/main/numpy_sec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing :", arr[2:7])
print("With Step :", arr[1:8:2])
print("Negative indexing :", arr[-3])

Basic Slicing : [3 4 5 6 7]
With Step : [2 4 6 8]
Negative indexing : 8


In [ ]:
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element :", arr_2D[1, 2]) # it's only allow numpy not regular python lan
print("Entire row :", arr_2D[1])
print("Entire colunm :", arr_2D[:, 1])

Specific element : 6
Entire row : [4 5 6]
Entire colunm : [2 5 8]


In [ ]:
unsorted = np.array([2, 5, 6, 9, 3, 5, 4, 7, 1, 8])
print("Stored array :", np.sort(unsorted)) # Bsics

arr_2D = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column :", np.sort(arr_2D, axis = 0))

Stored array : [1 2 3 4 5 5 6 7 8 9]
Sorted 3D array by column : [[1 1]
 [2 2]
 [3 3]]


In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers :", even_number)


Even numbers : [ 2  4  6  8 10]


In [ ]:
mask = numbers > 5
print("Numbers greater than 5 :", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


In [ ]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where : ", numbers [where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes :", a.shape == b.shape)


Compatibility shapes : True


In [ ]:
Original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_newRow = np.vstack((Original, new_row))
print(Original)
print("with new Row :",with_newRow)

new_col = np.array([[7], [8]])
with_newCol = np.hstack((Original, new_col))
print("with new column :", with_newCol)

with_newRow = np.array

[[1 2]
 [3 4]]
with new Row : [[1 2]
 [3 4]
 [5 6]]
with new column : [[1 2 7]
 [3 4 8]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion :", deleted)

Array after deletion : [1 2 4 5]
