<a href="https://colab.research.google.com/github/codewithvishuuu/ML-crash-course/blob/main/third_numpyfun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([3, 5, 9, 7, 6, 8])
matrix = np.array([[3, 2, 1],
                   [6, 8, 9],
                   [5, 4, 7]])

In [ ]:
s = np.sum(arr)
print("Sum of array :", s)

s = np.sum(matrix)
print("Sum of matrix :", s)
s = np.sum(matrix, axis=0) #column
print(s)
s = np.sum(matrix, axis=1) #ROW
print(s)

Sum of array : 38
Sum of matrix : 45
[14 14 17]
[ 6 23 16]


In [ ]:
p = np.prod(arr)
print("Product of array :", p)
print(matrix)

Product of array : 45360
[[3 2 1]
 [6 8 9]
 [5 4 7]]


In [ ]:
mi = np.min(arr)
print("minimum value of array :", mi)
ma = np.max(arr)
print("maximum value of array :", ma)

minimum value of array : 3
maximum value of array : 9


In [ ]:
print(ma-mi) #Range of array
p = np.ptp(arr)
print(p)

6
6


In [ ]:
cs = np.cumsum(arr)
print(cs)

cp = np.cumprod(arr)
print(cp)

[ 3  8 17 24 30 38]
[    3    15   135   945  5670 45360]


In [ ]:
a = np.all(arr>3)
print(a)

an = np.any(arr>3)
print(an)

False
True


In [ ]:
cnz =np.count_nonzero(arr)
print(cnz)

6


In [ ]:
am = np.argmax(arr)
print(am)

am = np.argmin(arr)
print(am)

2
0


In [ ]:
s = np.size(arr)
print(s)

m = np.size(matrix)
print(s)

6
6


In [ ]:
nd = np.ndim(arr)
print(nd)

nd = np.ndim(matrix)
print(nd)

1
2


In [ ]:
s = np.shape(matrix)
print(s)

s = np.shape(arr)
print(s)

(3, 3)
(6,)


Statistical Functions in NumPy

In [ ]:
arr = np.array([35, 65, 95, 25, 54, 75, 12])
print("Mean :", np.mean(arr))
print("Median :", np.median(arr))

Mean : 51.57142857142857
Median : 54.0
